import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
await fs.mkdir('artifacts',{recursive:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173',{waitUntil:'domcontentloaded',timeout:60000});await page.waitForFunction(()=>window.__world);await page.waitForTimeout(1500);await page.screenshot({path:'artifacts/desktop.jpg',quality:90});
await page.locator('#enter').click();await page.waitForTimeout(300);if(await page.locator('#menu').isVisible())await page.locator('#resume').click();
await page.keyboard.down('KeyW');await page.waitForFunction(()=>window.__world.state.position.z<12);await page.keyboard.up('KeyW');const state=await page.evaluate(()=>window.__world.state);if(state.position.z>=12)throw Error('W movement failed: '+JSON.stringify(state));await page.screenshot({path:'artifacts/game.jpg',quality:90});
await page.keyboard.press('KeyR');await page.waitForTimeout(100);const reset=await page.evaluate(()=>window.__world.state);if(Math.abs(reset.position.z-13)>.1)throw Error('Reset failed');
await page.close();const mobile=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,deviceScaleFactor:1});const mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.message));await mp.goto('http://localhost:5173',{waitUntil:'domcontentloaded',timeout:60000});await mp.waitForFunction(()=>window.__world);await mp.locator('#enter').tap();await mp.waitForTimeout(500);await mp.screenshot({path:'artifacts/mobile.jpg',quality:90});
if(!await mp.locator('#joystick').isVisible())throw Error('Touch joystick missing');
const cdp=await mobile.newCDPSession(mp);const jr=await mp.locator('#joystick').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:jr.x+jr.width/2,y:jr.y+jr.height/2-35}]});await mp.waitForFunction(()=>window.__world.state.position.z<12.5);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const ms=await mp.evaluate(()=>window.__world.state);if(ms.position.z>=12.9)throw Error('Touch movement failed '+JSON.stringify(ms));
await mp.waitForFunction(()=>window.__world.state.grounded);await mp.locator('#touch-jump').tap();await mp.waitForFunction(()=>window.__world.state.position.y>0,{},{timeout:5000});
await mp.setViewportSize({width:390,height:844});await mp.screenshot({path:'artifacts/mobile-portrait.jpg',quality:90});
console.log(JSON.stringify({desktop:state,mobile:ms,errors},null,2));await browser.close();if(errors.length)process.exit(1);
