import {chromium} from '@playwright/test';
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1000,height:700}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:5173');await page.waitForFunction(()=>window.__world);await page.locator('#enter').click();await page.waitForTimeout(300);
const state=()=>page.evaluate(()=>window.__world.state);
async function look(yaw=0,pitch=0){const s=await state();await page.evaluate(({dx,dy})=>document.querySelector('canvas').dispatchEvent(new PointerEvent('pointermove',{movementX:dx,movementY:dy})),{dx:(s.yaw-yaw)/.0025,dy:(s.pitch-pitch)/.0025});await page.waitForTimeout(100);}
async function axis(axis,value){await look();const initial=await state(),sign=Math.sign(value-initial.position[axis]);if(!sign)return;const key=axis==='x'?(sign>0?'KeyD':'KeyA'):(sign>0?'KeyS':'KeyW');await page.keyboard.down(key);const start=Date.now();while(true){const s=await state();if((value-s.position[axis])*sign<=.12)break;if(Date.now()-start>15000)throw Error('Movement blocked: '+axis+' to '+value+' '+JSON.stringify(s));await page.waitForTimeout(40);}await page.keyboard.up(key);}
async function aim(x,y,z){const s=await state(),dx=x-s.position.x,dz=z-s.position.z;await look(Math.atan2(-dx,-dz),Math.atan2(y-(s.position.y+1.66),Math.hypot(dx,dz)));}
try{
await axis('x',-5.8);await axis('z',7.5);await aim(-5.8,.7,6);await page.waitForFunction(()=>window.__world.state.target);await page.keyboard.press('KeyE');await page.waitForTimeout(150);if((await state()).picked!==1)throw Error('Basket pickup failed '+JSON.stringify(await state()));
await axis('x',3.5);await axis('z',6.5);await aim(3.5,.2,5);await page.waitForFunction(()=>window.__world.state.target);await page.keyboard.press('KeyE');await page.waitForTimeout(150);if((await state()).picked!==2)throw Error('Wood pickup failed');
await axis('x',-.58);await axis('z',3.2);await aim(-.58,1.5,1.65);await page.waitForFunction(()=>window.__world.state.target);await page.keyboard.press('KeyE');await page.waitForTimeout(500);if(!(await state()).doorOpen[0])throw Error('Door did not open');await axis('z',.4);await axis('x',-3);await axis('z',-.7);await aim(-3,.9,-2.2);await page.waitForFunction(()=>window.__world.state.target);await page.keyboard.press('KeyE');await page.waitForTimeout(150);if((await state()).picked!==3)throw Error('Cup pickup failed');
await page.keyboard.press('KeyR');await axis('x',8.4);await axis('z',-.8);const balcony=await state();if(Math.abs(balcony.position.y-3.3)>.05)throw Error('Stairs failed '+JSON.stringify(balcony));await axis('x',7);console.log(JSON.stringify({result:'all three pickups, opening door, entering house, stair ascent and balcony passed',state:await state(),errors},null,2));
}finally{await browser.close();}
if(errors.length)process.exit(1);
