import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
await mkdir('artifacts', { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Users/23636/AppData/Local/Google/Chrome/Application/chrome.exe', headless: true, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 }, deviceScaleFactor: 1 });
page.on('pageerror', e => console.error('PAGE ERROR:', e));
page.on('console', e => { if (e.type() === 'error') console.error('CONSOLE:', e.text()); });
await page.goto('http://127.0.0.1:5173/');
await page.waitForFunction(() => window.__scene?.ready, { timeout: 60000 });
await page.waitForFunction(() => document.querySelector('#loading').classList.contains('is-hidden'));
await page.waitForTimeout(2500);
await page.screenshot({ path: 'artifacts/desktop-initial.png' });
console.log(await page.evaluate(() => ({ drawCalls: __scene.renderer.info.render.calls, triangles: __scene.renderer.info.render.triangles, bounds: document.querySelector('#scene').getBoundingClientRect().toJSON() })));
await browser.close();
