import * as THREE from 'three';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { buildHouse } from './house.js';
import { buildEnvironment } from './environment.js';
import './style.css';
import {intersects,floorAt} from './physics.js';
const $=s=>document.querySelector(s),touch=matchMedia('(pointer:coarse)').matches;
const scene=new THREE.Scene();scene.background=new THREE.Color('#b4cbd6');scene.fog=new THREE.Fog('#b4cbd6',65,175);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.08,240);camera.rotation.order='YXZ';
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('#welcome').innerHTML='<h1>暂时无法打开三维场景</h1><p>请使用支持 WebGL 2 的浏览器，并开启硬件加速后重试。</p>';throw e;}
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,touch?1.4:1.8));renderer.shadowMap.enabled=!touch;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;$('#world').append(renderer.domElement);
const pmrem=new THREE.PMREMGenerator(renderer);const envRoom=new RoomEnvironment();scene.environment=pmrem.fromScene(envRoom,.04).texture;scene.environmentIntensity=.38;envRoom.dispose();pmrem.dispose();
scene.add(new THREE.HemisphereLight('#e6f1ff','#686852',1.8));const sun=new THREE.DirectionalLight('#fff6e6',2.8);sun.position.set(-23,44,28);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-32,right:32,top:32,bottom:-32,near:1,far:100});sun.shadow.bias=-.0005;scene.add(sun);
const {colliders,interactables,doors,materials,raycastRoots}=buildHouse(scene,renderer);
const environment=buildEnvironment({THREE,scene,renderer});
let active=false,started=false,yaw=0,pitch=0,vy=0,grounded=true,feet=0,elapsed=0,current=null;const position=new THREE.Vector3(0,0,13),keys=new Set(),move={x:0,y:0};let picked=0;
const ray=new THREE.Raycaster();function toast(s){$('#toast').textContent=s;$('#toast').style.opacity=1;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.opacity=0,3000);}
function setActive(v){active=v;keys.clear();move.x=move.y=0;$('#stick').style.transform='';}
function enter(){started=true;document.body.classList.add('playing');for(const id of ['welcome','scene-label','landing-footer'])$('#'+id).hidden=true;$('#game-ui').hidden=false;if($('#menu').open)$('#menu').close();setActive(true);if(!touch)renderer.domElement.requestPointerLock?.()?.catch(()=>toast('点击画面锁定鼠标，也可按住画面拖动环顾'));}
$('#enter').onclick=enter;$('#resume').onclick=enter;$('#close-menu').onclick=()=>{if(started)enter();else $('#menu').close();};function menu(){setActive(false);document.exitPointerLock?.();if(!$('#menu').open)$('#menu').showModal();}$('#help').onclick=menu;$('#pause').onclick=menu;
$('#menu').addEventListener('cancel',e=>{e.preventDefault();if(started)enter();else $('#menu').close();});
document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&active&&!touch)menu();});
function reset(){position.set(0,0,13);feet=0;vy=0;yaw=0;pitch=0;toast('已回到院子入口');}$('#reset').onclick=reset;
function interact(){if(!active||!current)return;if(current.type==='door'){current.open=!current.open;current.barrier.disabled=current.open;toast(current.open?'木门已打开':'木门已关上');}else{current.picked=true;current.root.visible=false;scene.remove(current.root);picked++;[...$('#inventory').children].find(e=>e.textContent.includes(current.name))?.classList.add('collected');[...$('#inventory').children].forEach(e=>{if(e.classList.contains('collected'))e.textContent=e.textContent.replace('○','✓');});toast('已拾取'+current.name);if(picked===3){$('#quest-status').textContent='全部找到了。再去阳台看看山吧。';toast('三件小物已收好，享受山居时光。');}}current=null;}
function jump(){if(active&&grounded){vy=5;grounded=false;}}
addEventListener('keydown',e=>{if(!active)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='KeyE'&&!e.repeat)interact();if(e.code==='KeyR'&&!e.repeat)reset();if(e.code==='Space'&&!e.repeat)jump();});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{if(active)menu();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)menu();});
let drag=null;renderer.domElement.addEventListener('pointerdown',e=>{if(!active)return;if(e.pointerType==='touch'&&e.clientX<innerWidth*.4)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(!active)return;let dx=0,dy=0;if(document.pointerLockElement){dx=e.movementX;dy=e.movementY;}else if(drag?.id===e.pointerId){dx=e.clientX-drag.x;dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;}yaw-=dx*.0025;pitch=THREE.MathUtils.clamp(pitch-dy*.0025,-1.35,1.35);});for(const ev of ['pointerup','pointercancel'])renderer.domElement.addEventListener(ev,()=>drag=null);
const joystick=$('#joystick');let joyId=null;function joy(e){const r=joystick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,l=Math.max(38,Math.hypot(dx,dy));move.x=dx/l;move.y=-dy/l;$('#stick').style.transform=`translate(${move.x*32}px,${-move.y*32}px)`;}joystick.onpointerdown=e=>{joyId=e.pointerId;joystick.setPointerCapture(e.pointerId);joy(e);};joystick.onpointermove=e=>{if(joyId===e.pointerId)joy(e);};for(const ev of ['pointerup','pointercancel','lostpointercapture'])joystick.addEventListener(ev,()=>{joyId=null;move.x=move.y=0;$('#stick').style.transform='';});$('#touch-interact').onclick=interact;$('#touch-jump').onclick=jump;
$('#quality').value=touch?'low':'high';$('#quality').onchange=e=>{const high=e.target.value==='high';renderer.setPixelRatio(Math.min(devicePixelRatio,high?1.8:1));renderer.shadowMap.enabled=high;environment.setQuality?.(high);materials.forEach(m=>m.needsUpdate=true);};
let audioCtx=null,audioGain=null,audioOn=false;$('#sound').onclick=async()=>{try{if(!audioCtx){audioCtx=new AudioContext();const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*3,audioCtx.sampleRate);const data=buffer.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){last=(last+.02*(Math.random()*2-1))/1.02;data[i]=last*3.5;}const noise=audioCtx.createBufferSource();noise.buffer=buffer;noise.loop=true;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=600;audioGain=audioCtx.createGain();audioGain.gain.value=0;noise.connect(filter).connect(audioGain).connect(audioCtx.destination);noise.start();}await audioCtx.resume();audioOn=!audioOn;audioGain.gain.setTargetAtTime(audioOn?.15:0,audioCtx.currentTime,.4);$('#sound').textContent='声音 '+(audioOn?'开':'关');}catch{toast('此浏览器暂时无法开启环境音');}};
function blocked(x,z){return colliders.some(b=>!b.disabled&&intersects(x,z,feet,b));}
function update(dt,probe=true){let forward=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)+move.y;let side=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+move.x;const len=Math.max(1,Math.hypot(forward,side));forward/=len;side/=len;const speed=keys.has('ShiftLeft')?4.6:2.8,dx=(side*Math.cos(yaw)-forward*Math.sin(yaw))*speed*dt,dz=(-forward*Math.cos(yaw)-side*Math.sin(yaw))*speed*dt;const nx=THREE.MathUtils.clamp(position.x+dx,-28,28),nz=THREE.MathUtils.clamp(position.z+dz,-22,48);if(!blocked(nx,position.z))position.x=nx;if(!blocked(position.x,nz))position.z=nz;const floor=Math.max(floorAt(position.x,position.z,feet),environment.terrainHeight(position.x,position.z));vy-=12*dt;feet+=vy*dt;if(feet<=floor){feet=floor;vy=0;grounded=true;}else grounded=false;camera.position.set(position.x,feet+1.66+(grounded&&Math.abs(forward)+Math.abs(side)>.1?Math.sin(elapsed*10)*.026:0),position.z);camera.rotation.set(pitch,yaw,0);if(!probe)return;$('#location').textContent=feet>2.9&&position.x<9.4&&position.x>-7.4&&position.z<3.2&&position.z>-5.9?'二楼 · 山景阳台':position.z<1.5&&Math.abs(position.x)<6.3?'屋内 · 日常之间':'山间小院';
ray.setFromCamera(new THREE.Vector2(0,0),camera);ray.far=2.7;const hits=ray.intersectObjects(raycastRoots.filter(root=>root.visible),true);current=null;for(const hit of hits){if(!hit.object.visible)continue;const target=hit.object.userData.target;if(target&&!target.picked){current=target;break;}if(hit.distance>.15)break;}$('#interaction').hidden=!current;if(current)$('#interaction').textContent=(touch?'点击互动':'[E]')+' '+(current.type==='door'?(current.open?'关上':'打开'):'拾取')+current.name;
}
$('#overview').onclick=()=>{setActive(false);started=false;document.exitPointerLock?.();document.body.classList.remove('playing');for(const id of ['welcome','scene-label','landing-footer'])$('#'+id).hidden=false;$('#game-ui').hidden=true;$('#menu').close();};
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.15);elapsed+=dt;if(!started){camera.fov=innerWidth/innerHeight<1?60:42;camera.position.set(13.8,11.8,17.5);camera.lookAt(.3,5.2,-.7);camera.updateProjectionMatrix();camera.clearViewOffset();}else{camera.fov=58;camera.updateProjectionMatrix();camera.clearViewOffset();if(active){let remaining=dt;while(remaining>0){const step=Math.min(.025,remaining);remaining-=step;update(step,remaining<.0001);}}}for(const d of doors){d.angle=THREE.MathUtils.damp(d.angle,d.open?-Math.PI*.55:0,9,dt);d.pivot.rotation.y=d.angle;}renderer.render(scene,camera);}animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
// Read-only diagnostics for automated smoke checks.
window.__world={get state(){return {active,yaw,pitch,grounded,target:current?.name,position:{x:position.x,y:feet,z:position.z},picked,doorOpen:doors.map(d=>d.open),environment:environment.stats,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles};}};
