import * as THREE from 'three';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
import './style.css';
import {intersects,floorAt} from './physics.js';
const $=s=>document.querySelector(s),touch=matchMedia('(pointer:coarse)').matches;
const scene=new THREE.Scene();scene.background=new THREE.Color('#b4c8c4');scene.fog=new THREE.Fog('#b4c8c4',45,145);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.08,240);camera.rotation.order='YXZ';
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('#welcome').innerHTML='<h1>暂时无法打开三维场景</h1><p>请使用支持 WebGL 2 的浏览器，并开启硬件加速后重试。</p>';throw e;}
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,touch?1.4:1.8));renderer.shadowMap.enabled=!touch;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.22;$('#world').append(renderer.domElement);
scene.add(new THREE.HemisphereLight('#e4efff','#778258',2.3));const sun=new THREE.DirectionalLight('#fff0cc',3.2);sun.position.set(-25,40,22);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-32,right:32,top:32,bottom:-32,near:1,far:100});sun.shadow.bias=-.0005;scene.add(sun);
const materials={};function mat(color,roughness=.85,metalness=0){const key=color+roughness+metalness;return materials[key]??=new THREE.MeshStandardMaterial({color,roughness,metalness});}
const colliders=[],interactables=[];const boxGeo=new THREE.BoxGeometry(1,1,1);function box(x,y,z,w,h,d,color,solid=false,parent=scene){const m=new THREE.Mesh(boxGeo,typeof color==='string'?mat(color):color);m.position.set(x,y,z);m.scale.set(w,h,d);m.castShadow=true;m.receiveShadow=true;parent.add(m);if(solid)colliders.push({minX:x-w/2,maxX:x+w/2,minZ:z-d/2,maxZ:z+d/2,minY:y-h/2,maxY:y+h/2});return m;}
function cylinder(x,y,z,r,h,color,parent=scene,r2=r){const m=new THREE.Mesh(new THREE.CylinderGeometry(r2,r,h,8),mat(color));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function sphere(x,y,z,r,color,parent=scene){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(r,1),mat(color));m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m;}
let seed=529;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
// Ground, approach, vegetable beds and a ring of wooded hills.
box(0,-.22,0,220,.4,220,'#7f9060');box(0,-.045,5,21,.1,22,'#b5b09a');box(-2,-.025,30,4,.08,32,'#b7af94');
for(let i=0;i<45;i++){const z=12+i*.67;box(-2+(rand()-.5)*.3,.035,z,2.9,.07,.45,'#aaa890');}
for(let i=0;i<24;i++){const a=i/24*Math.PI*2;const m=sphere(Math.sin(a)*85,-5,Math.cos(a)*85,18+rand()*18,i%2?'#778e73':'#8a9e81');m.scale.y=.6+rand()*.65;}
const trunkGeo=new THREE.CylinderGeometry(.13,.27,3.7,6),leafGeo=new THREE.IcosahedronGeometry(1,1);const treeTrunks=new THREE.InstancedMesh(trunkGeo,mat('#665e45'),170),treeLeaves=new THREE.InstancedMesh(leafGeo,mat('#4f7048'),510);const dummy=new THREE.Object3D();let ti=0;
for(let i=0;i<170;i++){let x=(rand()-.5)*130,z=(rand()-.5)*120;if(Math.abs(x)<13&&z>-10&&z<47){i--;continue;}const s=.75+rand()*1.4;dummy.position.set(x,1.8*s,z);dummy.scale.set(s,s,s);dummy.updateMatrix();treeTrunks.setMatrixAt(ti,dummy.matrix);for(let j=0;j<3;j++){dummy.position.set(x+(j-1)*s*.6,(3.6+j*.8)*s,z);dummy.scale.set((2.2-j*.35)*s,(1.8-j*.2)*s,(2-j*.2)*s);dummy.updateMatrix();treeLeaves.setMatrixAt(ti*3+j,dummy.matrix);treeLeaves.setColorAt(ti*3+j,new THREE.Color().setHSL(.24+rand()*.06,.23+rand()*.17,.24+rand()*.12));}ti++;}treeTrunks.castShadow=true;treeLeaves.castShadow=true;scene.add(treeTrunks,treeLeaves);
for(let i=0;i<6;i++){box(-11,.13,3+i*1.9,3,.25,1.4,'#6c6547');for(let j=0;j<7;j++){const plant=sphere(-12.1+j*.36,.38,3+i*1.9,.22,'#567646');plant.scale.y=.65;}}
// House: two inhabited levels, an attic, broad eaves and a wraparound veranda.
const wall='#e5e2d6',concrete='#b5b6aa',frame='#424b49';
for(const y of [0,3.3,6.6])box(0,y-.1,-1.5,14.6,.22,8.1,wall);
box(1,3.18,-1.6,16.8,.24,8.2,concrete);box(0,6.58,-1.5,16,.3,9,wall);
for(const y of [1.55,4.95]){box(-6.3,y,-1.7,.3,3.1,6.6,wall,true);box(6.3,y,-1.7,.3,3.1,6.6,wall,true);box(0,y,-4.9,12.8,3.1,.3,wall,true);
for(const x of [-5.9,-2.9,2.9,5.9])box(x,y,1.55,x===-2.9||x===2.9?1.25:.8,3.1,.3,wall,true);
box(0,y+1.23,1.55,5.1,.64,.3,wall,true);
for(const x of [-1.75,1.75])box(x,y,1.55,1.1,3.1,.3,wall,true);
for(const x of [-4.5,4.5]){box(x,y-.95,1.55,2.2,1.2,.3,wall,true);box(x,y+1.2,1.55,2.2,.7,.3,wall,true);windowAt(x,y+.05,1.72,2.1,1.65);}
box(0,y,-1.4,.16,3.1,4.3,wall,true);
}
function windowAt(x,y,z,w,h){box(x,y,z,w+.12,h+.12,.1,frame);box(x,y,z+.055,w-.09,h-.09,.035,mat('#627f7c',.2,.45));for(const dx of [-w/2,0,w/2])box(x+dx,y,z+.09,.055,h,.055,frame);box(x,y-.15,z+.1,w,.045,.055,frame);}
// Openable double doors leave a real passage through the facade.
const doors=[];for(const level of [0,3.3]){const pivot=new THREE.Group();pivot.position.set(-1.15,level,1.64);scene.add(pivot);box(.57,1.38,0,1.14,2.76,.12,frame,false,pivot);box(.57,1.8,.08,.88,1.3,.04,mat('#587472',.25,.4),false,pivot);box(1.02,1.1,.12,.045,.28,.055,'#c1b998',false,pivot);const other=box(.6,level+1.38,1.64,1.2,2.76,.12,frame,true);windowAt(.6,level+1.85,1.72,.91,1.16);const barrier={minX:-1.2,maxX:0,minZ:1.4,maxZ:1.85,minY:level,maxY:level+2.8,door:true};colliders.push(barrier);const target={type:'door',name:'木门',root:pivot,pivot,barrier,open:false,angle:0};doors.push(target);interactables.push(target);for(const x of [-1.42,1.42])box(x,level+1.48,1.74,.22,2.7,.025,'#a44735');}
// Upper attic.
box(0,7.38,-1.7,12.8,1.45,6.6,'#c0beb0');for(const x of [-4.3,0,4.3])windowAt(x,7.38,1.64,2.3,.85);
const roofMat=mat('#536a72',.75,.08);for(const side of [-1,1]){const slope=box(0,8.65,-1.7+side*1.85,14.4,.15,4.35,roofMat);slope.rotation.x=side*.47;for(let x=-7.1;x<=7.1;x+=.26){const tile=box(x,8.72,-1.7+side*1.85,.065,.065,4.4,'#758994');tile.rotation.x=side*.47;}for(let r=0;r<10;r++){const z=-1.7+side*r*.4;box(0,9.64-r*.203,z,14.4,.055,.07,'#425b67');}}cylinder(0,9.69,-1.7,.1,14.6,'#607780').rotation.z=Math.PI/2;
// Metal balcony railings; collision rails prevent walking into empty space.
function rail(x1,z1,x2,z2,y){const length=Math.hypot(x2-x1,z2-z1),n=Math.ceil(length/.29);for(let i=0;i<=n;i++)cylinder(x1+(x2-x1)*i/n,y+.53,z1+(z2-z1)*i/n,i%6===0?.045:.018,1.06,'#a3aaa2');for(const h of [.18,.85,1.08]){const bar=box((x1+x2)/2,y+h,(z1+z2)/2,length,.035,.04,mat('#b7beb4',.3,.7));bar.rotation.y=-Math.atan2(z2-z1,x2-x1);}colliders.push({minX:Math.min(x1,x2)-.05,maxX:Math.max(x1,x2)+.05,minZ:Math.min(z1,z2)-.05,maxZ:Math.max(z1,z2)+.05,minY:y,maxY:y+1.1});}
rail(-7.2,2.45,7.45,2.45,3.3);rail(-7.2,2.45,-7.2,-5.5,3.3);rail(-7.2,-5.5,9.2,-5.5,3.3);rail(9.2,-5.5,9.2,0,3.3);
for(let i=0;i<22;i++){const h=(i+1)*3.3/22;box(8.4,h/2,8-(i+.5)*8/22,1.8,h,8/22,concrete);}
for(const x of [7.48,9.32]){for(let i=0;i<12;i++)cylinder(x,(1-i/11)*3.3+.5,i/11*8,.035,1,'#a3aaa2');const bar=box(x,2.18,4,.055,.055,8.65,mat('#bbc1b5',.3,.7));bar.rotation.x=Math.atan(3.3/8);}
// Furnished rooms, courtyard details.
for(const level of [0,3.3]){box(-3,level+.69,-2.2,1.7,.12,1.2,'#94724d',true);for(const x of [-3.7,-2.3])for(const z of [-2.65,-1.75])box(x,level+.32,z,.09,.64,.09,'#796144');box(3.8,level+.29,-3.1,2.7,.58,1.3,'#747e66',true);box(3.8,level+.77,-3.64,2.7,.65,.15,'#8c957d');box(1.8,level+.78,-4.6,1.4,1.5,.4,'#9a805e',true);box(-4.9,level+.18,-2.4,.7,.36,.7,'#8e704e',true);}
box(-6.4,.38,6,2.4,.12,.7,'#928361',true);for(const x of [-7.3,-5.5])box(x,.17,6,.18,.34,.6,'#737669');
for(const [x,z] of [[-6,2.4],[5.8,2.6],[-7.5,8],[10,-3]]){cylinder(x,.3,z,.35,.6,'#a17a5c',scene,.43);for(let i=0;i<6;i++){const leaf=sphere(x+(rand()-.5)*.6,.7+rand()*.4,z+(rand()-.5)*.6,.25,'#5e794a');leaf.scale.y=1.6;}}
for(let i=0;i<9;i++){const log=cylinder(-7.9+(i%3)*.23,.12+Math.floor(i/3)*.2,3,.1,1.3,'#827052');log.rotation.x=Math.PI/2;}
for(let i=0;i<45;i++){const x=(rand()-.5)*50,z=rand()*48-15;if(Math.abs(x)<10&&z<18)continue;const rock=sphere(x,.13,z,.2+rand()*.45,'#92978a');rock.scale.y=.6;}
function item(name,x,y,z,kind){const g=new THREE.Group();g.position.set(x,y,z);scene.add(g);if(kind==='basket'){cylinder(0,.18,0,.25,.35,'#bc9760',g,.34);for(let i=0;i<6;i++)cylinder(0,.04+i*.055,0,.26+i*.013,.016,'#80643f',g);const handle=new THREE.Mesh(new THREE.TorusGeometry(.29,.025,5,20,Math.PI),mat('#836843'));handle.position.y=.36;g.add(handle);}else if(kind==='wood'){for(let i=0;i<3;i++){const log=cylinder((i-1)*.13,.14,0,.09,.65,'#a27e4e',g);log.rotation.x=Math.PI/2;}}else{cylinder(0,.12,0,.11,.24,'#c6d7bd',g);const handle=new THREE.Mesh(new THREE.TorusGeometry(.08,.022,6,12),mat('#c6d7bd'));handle.position.set(.12,.13,0);g.add(handle);}const target={type:'item',name,root:g,picked:false};g.traverse(o=>o.userData.target=target);interactables.push(target);}
item('竹篮',-5.8,.46,6,'basket');item('柴木',3.5,.04,5,'wood');item('陶杯',-3,.77,-2.2,'cup');doors.forEach(d=>d.root.traverse(o=>o.userData.target=d));
// Merge static geometry by material: keep mobile draw calls low while retaining raycast occlusion.
const batches=new Map();scene.updateMatrixWorld(true);for(const mesh of [...scene.children]){if(!mesh.isMesh||mesh.isInstancedMesh)continue;const geometry=mesh.geometry.clone().applyMatrix4(mesh.matrixWorld);const list=batches.get(mesh.material)??[];list.push(geometry.index?geometry.toNonIndexed():geometry);batches.set(mesh.material,list);scene.remove(mesh);}for(const [material,geometries] of batches){const merged=new THREE.Mesh(mergeGeometries(geometries),material);merged.castShadow=true;merged.receiveShadow=true;scene.add(merged);geometries.forEach(g=>g.dispose());}
let active=false,started=false,yaw=0,pitch=0,vy=0,grounded=true,feet=0,elapsed=0,current=null;const position=new THREE.Vector3(0,0,13),keys=new Set(),move={x:0,y:0};let picked=0;
const ray=new THREE.Raycaster();function toast(s){$('#toast').textContent=s;$('#toast').style.opacity=1;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.opacity=0,3000);}
function setActive(v){active=v;keys.clear();move.x=move.y=0;$('#stick').style.transform='';}
function enter(){started=true;document.body.classList.add('playing');for(const id of ['welcome','scene-label','landing-footer'])$('#'+id).hidden=true;$('#game-ui').hidden=false;if($('#menu').open)$('#menu').close();setActive(true);if(!touch)renderer.domElement.requestPointerLock?.()?.catch(()=>toast('点击画面锁定鼠标，也可按住画面拖动环顾'));}
$('#enter').onclick=enter;$('#resume').onclick=enter;$('#close-menu').onclick=()=>{if(started)enter();else $('#menu').close();};function menu(){setActive(false);document.exitPointerLock?.();if(!$('#menu').open)$('#menu').showModal();}$('#help').onclick=menu;$('#pause').onclick=menu;
$('#menu').addEventListener('cancel',e=>{e.preventDefault();if(started)enter();else $('#menu').close();});
document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&active&&!touch)menu();});
function reset(){position.set(0,0,13);feet=0;vy=0;yaw=0;pitch=0;toast('已回到院子入口');}$('#reset').onclick=reset;
function interact(){if(!active||!current)return;if(current.type==='door'){current.open=!current.open;current.barrier.disabled=current.open;toast(current.open?'木门已打开':'木门已关上');}else{current.picked=true;current.root.visible=false;scene.remove(current.root);picked++;[...$('#inventory').children].find(e=>e.textContent.includes(current.name))?.classList.add('collected');[...$('#inventory').children].forEach(e=>{if(e.classList.contains('collected'))e.textContent=e.textContent.replace('○','✓');});toast('已拾取'+current.name);if(picked===3){$('#quest-status').textContent='全部找到了。再去阳台看看山吧。';toast('三件小物已收好，享受山居时光。');}}current=null;}
function jump(){if(active&&grounded){vy=5;grounded=false;}}
addEventListener('keydown',e=>{if(!active)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='KeyE'&&!e.repeat)interact();if(e.code==='KeyR'&&!e.repeat)reset();if(e.code==='Space'&&!e.repeat)jump();});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{if(active)menu();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)menu();});
let drag=null;renderer.domElement.addEventListener('pointerdown',e=>{if(!active)return;if(e.pointerType==='touch'&&e.clientX<innerWidth*.4)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(!active)return;let dx=0,dy=0;if(document.pointerLockElement){dx=e.movementX;dy=e.movementY;}else if(drag?.id===e.pointerId){dx=e.clientX-drag.x;dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;}yaw-=dx*.0025;pitch=THREE.MathUtils.clamp(pitch-dy*.0025,-1.35,1.35);});for(const ev of ['pointerup','pointercancel'])renderer.domElement.addEventListener(ev,()=>drag=null);
const joystick=$('#joystick');let joyId=null;function joy(e){const r=joystick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,l=Math.max(38,Math.hypot(dx,dy));move.x=dx/l;move.y=-dy/l;$('#stick').style.transform=`translate(${move.x*32}px,${-move.y*32}px)`;}joystick.onpointerdown=e=>{joyId=e.pointerId;joystick.setPointerCapture(e.pointerId);joy(e);};joystick.onpointermove=e=>{if(joyId===e.pointerId)joy(e);};for(const ev of ['pointerup','pointercancel','lostpointercapture'])joystick.addEventListener(ev,()=>{joyId=null;move.x=move.y=0;$('#stick').style.transform='';});$('#touch-interact').onclick=interact;$('#touch-jump').onclick=jump;
$('#quality').value=touch?'low':'high';$('#quality').onchange=e=>{const high=e.target.value==='high';renderer.setPixelRatio(Math.min(devicePixelRatio,high?1.8:1));renderer.shadowMap.enabled=high;Object.values(materials).forEach(m=>m.needsUpdate=true);};
let audioCtx=null,audioGain=null,audioOn=false;$('#sound').onclick=async()=>{try{if(!audioCtx){audioCtx=new AudioContext();const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*3,audioCtx.sampleRate);const data=buffer.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){last=(last+.02*(Math.random()*2-1))/1.02;data[i]=last*3.5;}const noise=audioCtx.createBufferSource();noise.buffer=buffer;noise.loop=true;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=600;audioGain=audioCtx.createGain();audioGain.gain.value=0;noise.connect(filter).connect(audioGain).connect(audioCtx.destination);noise.start();}await audioCtx.resume();audioOn=!audioOn;audioGain.gain.setTargetAtTime(audioOn?.15:0,audioCtx.currentTime,.4);$('#sound').textContent='声音 '+(audioOn?'开':'关');}catch{toast('此浏览器暂时无法开启环境音');}};
function blocked(x,z){return colliders.some(b=>!b.disabled&&intersects(x,z,feet,b));}
function update(dt){let forward=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)+move.y;let side=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+move.x;const len=Math.max(1,Math.hypot(forward,side));forward/=len;side/=len;const speed=keys.has('ShiftLeft')?4.6:2.8,dx=(side*Math.cos(yaw)-forward*Math.sin(yaw))*speed*dt,dz=(-forward*Math.cos(yaw)-side*Math.sin(yaw))*speed*dt;const nx=THREE.MathUtils.clamp(position.x+dx,-28,28),nz=THREE.MathUtils.clamp(position.z+dz,-22,48);if(!blocked(nx,position.z))position.x=nx;if(!blocked(position.x,nz))position.z=nz;const floor=floorAt(position.x,position.z,feet);vy-=12*dt;feet+=vy*dt;if(feet<=floor){feet=floor;vy=0;grounded=true;}else grounded=false;camera.position.set(position.x,feet+1.66+(grounded&&Math.abs(forward)+Math.abs(side)>.1?Math.sin(elapsed*10)*.026:0),position.z);camera.rotation.set(pitch,yaw,0);$('#location').textContent=feet>2.9?'二楼 · 山景阳台':position.z<1.5&&Math.abs(position.x)<6.3?'屋内 · 日常之间':'山间小院';
ray.setFromCamera(new THREE.Vector2(0,0),camera);ray.far=2.7;const hits=ray.intersectObjects(scene.children,true);current=null;for(const hit of hits){if(!hit.object.visible)continue;const target=hit.object.userData.target;if(target&&!target.picked){current=target;break;}if(hit.distance>.15)break;}$('#interaction').hidden=!current;if(current)$('#interaction').textContent=(touch?'点击互动':'[E]')+' '+(current.type==='door'?(current.open?'关上':'打开'):'拾取')+current.name;
}
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04);elapsed+=dt;if(!started){const drift=Math.sin(elapsed*.07)*1.3;camera.position.set(23+drift,13,28);camera.lookAt(0,3,-1);camera.setViewOffset(innerWidth,innerHeight,-innerWidth*.15,0,innerWidth,innerHeight);}else{camera.clearViewOffset();if(active)update(dt);}for(const d of doors){d.angle=THREE.MathUtils.damp(d.angle,d.open?-Math.PI*.55:0,9,dt);d.pivot.rotation.y=d.angle;}renderer.render(scene,camera);}animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
// Read-only diagnostics for automated smoke checks.
window.__world={get state(){return {active,yaw,pitch,grounded,target:current?.name,position:{x:position.x,y:feet,z:position.z},picked,doorOpen:doors.map(d=>d.open),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles};}};
